site_name: Py-RPAutom
dev_addr: localhost:9999
repo_url: https://github.com/aranseiki/py-rpautom
repo_name: py-rpautom
remote_branch: gh-pages
remote_name: origin

watch:
  - docs

nav:
  - Breve história: historia.md
  - Dependências do projeto: dependencias.md
  - Guia de automação web: guia_usuario/automacao_web.md
  - Guia de automação desktop: guia_usuario/automacao_desktop.md
  - Guia de utilitários python: guia_usuario/automacao_python.md
  - Sobre:
    - Notas de Release: sobre/release-notes.md
    - Licença: sobre/license.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

theme:
  name: material
  language: pt-BR

  hljs_languages:
      - yaml
      - python

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
