site_name: Py-RPAutom
dev_addr: localhost:9999
repo_url: https://github.com/aranseiki/py-rpautom
repo_name: py-rpautom
remote_branch: gh-pages
remote_name: origin

watch:
  - docs

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["py_rpautom"]
  - search

hooks:
  - docs/hooks/formatting.py

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

theme:
  name: material
  language: pt-BR
  locale: pt_BR

  hljs_languages:
      - yaml
      - python

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

nav:
  - Breve história: historia.md
  - Dependências do projeto: dependencias.md
  - Guia de automação web: guia_usuario/web_utils.md
  - Guia de automação desktop: guia_usuario/desktop_utils.md
  - Guia de utilitários python: guia_usuario/python_utils.md
  - Sobre:
    - Notas de Release: sobre/release-notes.md
    - Licença: sobre/license.md
